# Generated by Django 5.0.6 on 2026-07-16 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('closed', 'Cloture')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='reference.country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.currency')),
                ('donors', models.ManyToManyField(blank=True, related_name='projects', to='reference.donor')),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='reference.regionalhub')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='reference.sector')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectSdg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.sdg')),
            ],
            options={
                'db_table': 'project_sdg',
                'unique_together': {('project', 'sdg')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='sdgs',
            field=models.ManyToManyField(blank=True, related_name='projects', through='project.ProjectSdg', to='reference.sdg'),
        ),
    ]
