# Generated by Django 5.0.6 on 2026-07-16 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('reference', '0002_crosscuttingtheme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sdgs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='beneficiary_target_direct',
            field=models.PositiveIntegerField(blank=True, help_text='Cible beneficiaires directs (agrege — desagregation detaillee -> Module 6).', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='beneficiary_target_indirect',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contributing_sdgs',
            field=models.ManyToManyField(blank=True, help_text='ODD contributifs (0 ou plus).', related_name='projects', through='project.ProjectSdg', to='reference.sdg'),
        ),
        migrations.AddField(
            model_name='project',
            name='cross_cutting_themes',
            field=models.ManyToManyField(blank=True, related_name='projects', to='reference.crosscuttingtheme'),
        ),
        migrations.AddField(
            model_name='project',
            name='fragility_status',
            field=models.CharField(blank=True, choices=[('fcv', 'FCV'), ('pre_fcv', 'Pre-FCV'), ('stable', 'Stable')], help_text='Revu annuellement (RG-4.2).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gender_marker',
            field=models.CharField(blank=True, choices=[('0', 'Categorie 0 - Non cible'), ('1', 'Categorie 1 - Significatif'), ('2', 'Categorie 2 - Principal')], help_text='Marqueur OECD-DAC genre.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='geographic_typology',
            field=models.CharField(blank=True, choices=[('urban', 'Urbain'), ('peri_urban', 'Peri-urbain'), ('rural', 'Rural'), ('remote', 'Recule'), ('mixed_multi_district', 'Mixte multi-districts')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='implementation_modality',
            field=models.CharField(blank=True, choices=[('direct', 'Directe'), ('country_systems', 'Systemes pays'), ('ngo', 'ONG'), ('private', 'Prive'), ('multi_actor', 'Multi-acteurs'), ('hybrid', 'Hybride')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lifecycle_stage',
            field=models.CharField(choices=[('concept_note', 'Concept Note'), ('pipeline_taskforce_review', 'Pipeline Taskforce Review'), ('pipeline_taskforce_approved', 'Pipeline Taskforce Approved'), ('preparation_identification', 'Preparation / Identification'), ('trc_endorsed', 'TRC Endorsed'), ('ic_approved', 'IC Approved'), ('appraisal', 'Appraisal'), ('bed_approved', 'BED Approved'), ('effective', 'Effective'), ('implementing', 'Implementing'), ('mid_term_review', 'Mid-Term Review'), ('substantially_complete', 'Substantially Complete'), ('closed', 'Closed'), ('suspended', 'Suspended (exception)'), ('cancelled', 'Cancelled (exception)')], default='concept_note', help_text='13 etapes + 2 exceptions (SF-4).', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='official_reference_number',
            field=models.CharField(blank=True, help_text='Numero de reference officiel. Unicite controlee (rejet du doublon).', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pad_reference_file',
            field=models.FileField(blank=True, help_text="Declenche l'extraction IA (BRQ-1.14) si PDF lisible. TODO : brancher Azure Blob Storage en production (pas de base64).", null=True, upload_to='pad/'),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_sdg',
            field=models.ForeignKey(blank=True, help_text='ODD primaire (1 seul, obligatoire).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_as_primary', to='reference.sdg'),
        ),
        migrations.AddField(
            model_name='project',
            name='rio_marker_adaptation',
            field=models.CharField(choices=[('not_targeted', 'Non cible'), ('significant', 'Significatif'), ('principal', 'Principal')], default='not_targeted', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='rio_marker_biodiversity',
            field=models.CharField(choices=[('not_targeted', 'Non cible'), ('significant', 'Significatif'), ('principal', 'Principal')], default='not_targeted', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='rio_marker_desertification',
            field=models.CharField(choices=[('not_targeted', 'Non cible'), ('significant', 'Significatif'), ('principal', 'Principal')], default='not_targeted', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='rio_marker_mitigation',
            field=models.CharField(choices=[('not_targeted', 'Non cible'), ('significant', 'Significatif'), ('principal', 'Principal')], default='not_targeted', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='risk_rating',
            field=models.CharField(blank=True, choices=[('low', 'Faible'), ('moderate', 'Modere'), ('substantial', 'Substantiel'), ('high', 'Eleve')], help_text='Revu annuellement (RG-4.2).', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.SlugField(blank=True, help_text='Code projet interne — genere automatiquement si laisse vide (POL-1.05).', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.ForeignKey(help_text='Admin 0 (GADM). Obligatoire des Concept Note.', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='reference.country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Obligatoire des Concept Note.', max_length=255),
        ),
        migrations.CreateModel(
            name='ProjectStageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('concept_note', 'Concept Note'), ('pipeline_taskforce_review', 'Pipeline Taskforce Review'), ('pipeline_taskforce_approved', 'Pipeline Taskforce Approved'), ('preparation_identification', 'Preparation / Identification'), ('trc_endorsed', 'TRC Endorsed'), ('ic_approved', 'IC Approved'), ('appraisal', 'Appraisal'), ('bed_approved', 'BED Approved'), ('effective', 'Effective'), ('implementing', 'Implementing'), ('mid_term_review', 'Mid-Term Review'), ('substantially_complete', 'Substantially Complete'), ('closed', 'Closed'), ('suspended', 'Suspended (exception)'), ('cancelled', 'Cancelled (exception)')], max_length=30)),
                ('to_stage', models.CharField(choices=[('concept_note', 'Concept Note'), ('pipeline_taskforce_review', 'Pipeline Taskforce Review'), ('pipeline_taskforce_approved', 'Pipeline Taskforce Approved'), ('preparation_identification', 'Preparation / Identification'), ('trc_endorsed', 'TRC Endorsed'), ('ic_approved', 'IC Approved'), ('appraisal', 'Appraisal'), ('bed_approved', 'BED Approved'), ('effective', 'Effective'), ('implementing', 'Implementing'), ('mid_term_review', 'Mid-Term Review'), ('substantially_complete', 'Substantially Complete'), ('closed', 'Closed'), ('suspended', 'Suspended (exception)'), ('cancelled', 'Cancelled (exception)')], max_length=30)),
                ('transitioned_at', models.DateTimeField(auto_now_add=True)),
                ('justification', models.TextField(blank=True, help_text='Obligatoire pour tout retour arriere (POL-1.09).')),
                ('document_reference', models.CharField(blank=True, max_length=255)),
                ('dual_authorized_by', models.ForeignKey(blank=True, help_text='Second approbateur — requis pour les gates (TRC/IC/BED) et tout retour arriere.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_transitions_coauthorized', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions', to='project.project')),
                ('transitioned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_transitions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_stage_transition',
                'ordering': ['-transitioned_at'],
            },
        ),
    ]
