# Generated by Django 5.0.6 on 2026-07-17 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_sdgs_remove_project_status_and_more'),
        ('reference', '0002_crosscuttingtheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='country',
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, help_text='Code projet interne — genere automatiquement a partir du pays chef de file, une fois les pays du projet connus (POL-1.05). Voir apps.project.services.generate_project_code().', max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProjectCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lead', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_countries', to='reference.country')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_countries', to='project.project')),
            ],
            options={
                'db_table': 'project_country',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='countries',
            field=models.ManyToManyField(help_text="Admin 0 (GADM). Multi-pays autorise (R13 revisee) — le montant financier n'est jamais ventile par pays (R20). Voir pays chef de file sur ProjectCountry.is_lead.", related_name='projects', through='project.ProjectCountry', to='reference.country'),
        ),
        migrations.AddConstraint(
            model_name='projectcountry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_lead', True)), fields=('project',), name='unique_lead_country_per_project'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcountry',
            unique_together={('project', 'country')},
        ),
    ]
