# Generated by Django 5.0.6 on 2026-07-17 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_country_alter_project_code_and_more'),
        ('reference', '0002_crosscuttingtheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sector',
        ),
        migrations.AddField(
            model_name='project',
            name='primary_sector',
            field=models.ForeignKey(blank=True, help_text='Secteur primaire (obligatoire des Concept Note).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_as_primary', to='reference.sector'),
        ),
        migrations.CreateModel(
            name='ProjectSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.sector')),
            ],
            options={
                'db_table': 'project_sector',
                'unique_together': {('project', 'sector')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='contributing_sectors',
            field=models.ManyToManyField(blank=True, help_text='Secteurs contributifs (0 ou plus), sur le meme modele que les ODD.', related_name='projects', through='project.ProjectSector', to='reference.sector'),
        ),
    ]
