# Generated by Django 5.0.6 on 2026-07-17 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_sector_project_primary_sector_and_more'),
        ('reference', '0006_country_is_active_donor_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsdg',
            name='sdg',
            field=models.ForeignKey(help_text='PROTECT et non CASCADE : supprimer un ODD effacerait silencieusement la classification des projets qui le portent en contributif. Cf. POL-1.07 (pas de suppression definitive).', on_delete=django.db.models.deletion.PROTECT, to='reference.sdg'),
        ),
        migrations.AlterField(
            model_name='projectsector',
            name='sector',
            field=models.ForeignKey(help_text='PROTECT et non CASCADE : voir ProjectSdg.sdg.', on_delete=django.db.models.deletion.PROTECT, to='reference.sector'),
        ),
    ]
