# Generated by Django 5.0.6 on 2026-07-17 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_projectsdg_sdg_alter_projectsector_sector'),
        ('reference', '0006_country_is_active_donor_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFinancialEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Remarques libres sur la structure de financement.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_envelope', to='project.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelopes_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_financial_envelope',
            },
        ),
        migrations.CreateModel(
            name='FinancingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('isdb_oc', 'IsDB Ordinary Capital'), ('llf', 'LLF (fonds fiduciaire multi-donateurs)'), ('government', 'Gouvernement / contrepartie nationale'), ('co_financing', 'Co-financement')], help_text='Source de financement selon le vocabulaire LLF2.', max_length=20)),
                ('instrument', models.CharField(choices=[('loan', 'Pret'), ('grant', 'Don'), ('counterpart', 'Contrepartie'), ('co_financing', 'Co-financement')], help_text="Type d'instrument financier.", max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text="Montant dans la devise d'origine.", max_digits=16)),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text="Equivalent USD. Saisi manuellement avec la date de reference tant qu'aucun flux de taux de change n'est branche.", max_digits=16)),
                ('exchange_rate_date', models.DateField(blank=True, help_text='Date a laquelle le taux de change a ete applique.', null=True)),
                ('label', models.CharField(blank=True, help_text="Libelle libre, ex. 'Pret IsDB tranche 1'.", max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage dans le tableau de financement.")),
                ('currency', models.ForeignKey(help_text="Devise d'origine.", on_delete=django.db.models.deletion.PROTECT, to='reference.currency')),
                ('donor', models.ForeignKey(blank=True, help_text='Bailleur associe, si applicable (optionnel pour les lignes IsDB OC).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_contributions', to='reference.donor')),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financing_sources', to='project.projectfinancialenvelope')),
            ],
            options={
                'db_table': 'financing_source',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ComponentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('works', 'Travaux'), ('consulting', 'Conseil'), ('goods', 'Biens'), ('training', 'Formation'), ('operating', 'Fonctionnement')], max_length=20)),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Allocation indicative en USD.', max_digits=16)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_allocations', to='project.projectfinancialenvelope')),
            ],
            options={
                'db_table': 'component_allocation',
                'ordering': ['component'],
                'unique_together': {('envelope', 'component')},
            },
        ),
    ]
