# Generated by Django 5.0.6 on 2026-07-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectfinancialenvelope_financingsource_and_more'),
        ('project', '0006_sf6_financial_envelope'),
    ]

    operations = [
    ]
