# Generated by Django 5.0.6 on 2026-07-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_merge_20260717_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='next_reporting_due',
            field=models.DateField(blank=True, help_text='Premiere echeance de reporting.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reporting_frequency',
            field=models.CharField(blank=True, choices=[('quarterly', 'Trimestrielle'), ('semi_annual', 'Semestrielle'), ('annual', 'Annuelle')], max_length=15, null=True),
        ),
    ]
