# Generated by Django 5.0.6 on 2026-07-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_projectimplementingpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentallocation',
            name='component',
            field=models.CharField(choices=[('works', 'Works'), ('consulting', 'Consulting'), ('goods', 'Goods'), ('training', 'Training'), ('operating', 'Operating costs')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financingsource',
            name='instrument',
            field=models.CharField(choices=[('loan', 'Loan'), ('grant', 'Grant'), ('counterpart', 'Counterpart'), ('co_financing', 'Co-financing')], help_text="Type d'instrument financier.", max_length=20),
        ),
        migrations.AlterField(
            model_name='financingsource',
            name='source',
            field=models.CharField(choices=[('isdb_oc', 'IsDB Ordinary Capital'), ('llf', 'LLF (multi-donor trust fund)'), ('government', 'Government / national counterpart'), ('co_financing', 'Co-financing')], help_text='Source de financement selon le vocabulaire LLF2.', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='gender_marker',
            field=models.CharField(blank=True, choices=[('0', 'Category 0 — Not targeted'), ('1', 'Category 1 — Significant'), ('2', 'Category 2 — Principal')], help_text='Marqueur OECD-DAC genre.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='geographic_typology',
            field=models.CharField(blank=True, choices=[('urban', 'Urban'), ('peri_urban', 'Peri-urban'), ('rural', 'Rural'), ('remote', 'Remote'), ('mixed_multi_district', 'Mixed / multi-district')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='implementation_modality',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('country_systems', 'Country systems'), ('ngo', 'NGO'), ('private', 'Private'), ('multi_actor', 'Multi-actor'), ('hybrid', 'Hybrid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='reporting_frequency',
            field=models.CharField(blank=True, choices=[('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rio_marker_adaptation',
            field=models.CharField(choices=[('not_targeted', 'Not targeted'), ('significant', 'Significant'), ('principal', 'Principal')], default='not_targeted', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='rio_marker_biodiversity',
            field=models.CharField(choices=[('not_targeted', 'Not targeted'), ('significant', 'Significant'), ('principal', 'Principal')], default='not_targeted', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='rio_marker_desertification',
            field=models.CharField(choices=[('not_targeted', 'Not targeted'), ('significant', 'Significant'), ('principal', 'Principal')], default='not_targeted', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='rio_marker_mitigation',
            field=models.CharField(choices=[('not_targeted', 'Not targeted'), ('significant', 'Significant'), ('principal', 'Principal')], default='not_targeted', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='risk_rating',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('substantial', 'Substantial'), ('high', 'High')], help_text='Revu annuellement (RG-4.2).', max_length=15, null=True),
        ),
    ]
