# Generated by Django 5.0.6 on 2026-07-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_projectworkspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgadmscope',
            name='is_primary',
            field=models.BooleanField(default=False, help_text="Zone principale d'intervention (affichage prioritaire sur les cartes)."),
        ),
        migrations.AlterField(
            model_name='projectworkspace',
            name='m11_dashboard_ready',
            field=models.BooleanField(default=False, help_text='Dashboards par défaut créés.'),
        ),
        migrations.AlterField(
            model_name='projectworkspace',
            name='m2_results_ready',
            field=models.BooleanField(default=False, help_text='ToC verrouillée, Logframe initialisé.'),
        ),
        migrations.AlterField(
            model_name='projectworkspace',
            name='m3_workplan_ready',
            field=models.BooleanField(default=False, help_text='Workplan skeleton créé.'),
        ),
        migrations.AlterField(
            model_name='projectworkspace',
            name='m5_gis_ready',
            field=models.BooleanField(default=False, help_text='Périmètre GIS hérité de SF-7.'),
        ),
        migrations.AlterField(
            model_name='projectworkspace',
            name='m6_beneficiary_ready',
            field=models.BooleanField(default=False, help_text='Scaffold bénéficiaires créé.'),
        ),
        migrations.AlterField(
            model_name='projectworkspace',
            name='m9_risk_ready',
            field=models.BooleanField(default=False, help_text='Registre de risques amorcé.'),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='due_date',
            field=models.DateField(help_text='Date limite de soumission (fin de période + délai de grâce).'),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='label',
            field=models.CharField(blank=True, help_text="Ex. 'Q1 2026', 'S2 2026', 'Annual 2026'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='period_number',
            field=models.PositiveSmallIntegerField(help_text='Numéro séquentiel de la période (1, 2, 3…).'),
        ),
    ]
