# Generated by Django 5.0.6 on 2026-07-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_projectgadmscope_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='acronym',
            field=models.CharField(blank=True, help_text='Sigle court du projet (ex. PAAFS, WASH-IDN). Optionnel.', max_length=20),
        ),
    ]
