# Generated by Django 5.0.6 on 2026-07-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_projectimplementingpartner_role'),
        ('project', '0015_project_acronym'),
    ]

    operations = [
    ]
