# Generated by Django 5.0.6 on 2026-09-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_merge_project_sdgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reporting_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rio_marker_water',
            field=models.CharField(choices=[('not_targeted', 'Not targeted'), ('significant', 'Significant'), ('principal', 'Principal')], default='not_targeted', help_text='OECD-DAC Rio Marker — Water (Objectif de Eau).', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='label',
            field=models.CharField(blank=True, help_text="Ex. 'M03 2026', 'Q1 2026', 'S2 2026', 'Annual 2026'.", max_length=50),
        ),
    ]
