# Generated by Django 5.0.6 on 2026-09-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_classification_rework_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='acronym',
        ),
        migrations.RemoveField(
            model_name='project',
            name='code',
        ),
        migrations.AlterField(
            model_name='project',
            name='official_reference_number',
            field=models.CharField(blank=True, help_text="Numero de reference officiel, seul identifiant visible du projet (l'ancien code interne et le sigle ont ete retires). Unicite controlee.", max_length=50, null=True, unique=True),
        ),
    ]
