# Generated by Django 5.0.6 on 2026-09-11 11:16
#
# Lifecycle stages become the definitive September 2026 list: codes LS001 to
# LS018 are stored, the canonical names are the labels. The AlterFields only
# change choices, default and help_text, so they emit no SQL; the RunPython
# after them rewrites the stored values. Three stages are new and have no old
# value: LS007 IsDB Annual Work Plan (AWP), LS008 Preparations, LS011 Signature.

from django.db import migrations, models

OLD_TO_NEW = {
    "concept_note": "LS001",
    "pipeline_taskforce_review": "LS002",
    "pipeline_taskforce_approved": "LS003",  # now Pipeline Taskforce Selection
    "preparation_identification": "LS004",  # now Preparation/LLF
    "trc_endorsed": "LS005",  # now TRC clearance
    "ic_approved": "LS006",  # now IC endorsed
    "appraisal": "LS009",
    "bed_approved": "LS010",
    "effective": "LS012",
    "implementing": "LS013",
    "mid_term_review": "LS014",
    "substantially_complete": "LS015",
    "closed": "LS016",
    "suspended": "LS017",
    "cancelled": "LS018",
}
NEW_TO_OLD = {new: old for old, new in OLD_TO_NEW.items()}
NEW_ONLY = {"LS007", "LS008", "LS011"}


def _rewrite(apps, mapping):
    Project = apps.get_model("project", "Project")
    Transition = apps.get_model("project", "ProjectStageTransition")
    for source, target in mapping.items():
        Project.objects.filter(lifecycle_stage=source).update(lifecycle_stage=target)
        Transition.objects.filter(from_stage=source).update(from_stage=target)
        Transition.objects.filter(to_stage=source).update(to_stage=target)


def to_ls_codes(apps, schema_editor):
    _rewrite(apps, OLD_TO_NEW)


def to_old_values(apps, schema_editor):
    Project = apps.get_model("project", "Project")
    Transition = apps.get_model("project", "ProjectStageTransition")
    used = (
        Project.objects.filter(lifecycle_stage__in=NEW_ONLY).exists()
        or Transition.objects.filter(from_stage__in=NEW_ONLY).exists()
        or Transition.objects.filter(to_stage__in=NEW_ONLY).exists()
    )
    if used:
        raise RuntimeError(
            "Cannot reverse: rows use LS007, LS008 or LS011, which have no "
            "value in the old lifecycle."
        )
    _rewrite(apps, NEW_TO_OLD)


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_remove_project_code_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lifecycle_stage',
            field=models.CharField(choices=[('LS001', 'Concept Note'), ('LS002', 'Pipeline Taskforce Review'), ('LS003', 'Pipeline Taskforce Selection'), ('LS004', 'Preparation/LLF'), ('LS005', 'TRC clearance'), ('LS006', 'IC endorsed'), ('LS007', 'IsDB Annual Work Plan (AWP)'), ('LS008', 'Preparations'), ('LS009', 'Appraisal'), ('LS010', 'BED Approved'), ('LS011', 'Signature'), ('LS012', 'Effective'), ('LS013', 'Implementing'), ('LS014', 'Mid-Term Review'), ('LS015', 'Substantially Complete'), ('LS016', 'Closed'), ('LS017', 'Suspended'), ('LS018', 'Cancelled')], default='LS001', help_text='16 etapes + 2 exceptions (SF-4), code LS0xx.', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectstagetransition',
            name='from_stage',
            field=models.CharField(choices=[('LS001', 'Concept Note'), ('LS002', 'Pipeline Taskforce Review'), ('LS003', 'Pipeline Taskforce Selection'), ('LS004', 'Preparation/LLF'), ('LS005', 'TRC clearance'), ('LS006', 'IC endorsed'), ('LS007', 'IsDB Annual Work Plan (AWP)'), ('LS008', 'Preparations'), ('LS009', 'Appraisal'), ('LS010', 'BED Approved'), ('LS011', 'Signature'), ('LS012', 'Effective'), ('LS013', 'Implementing'), ('LS014', 'Mid-Term Review'), ('LS015', 'Substantially Complete'), ('LS016', 'Closed'), ('LS017', 'Suspended'), ('LS018', 'Cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='projectstagetransition',
            name='to_stage',
            field=models.CharField(choices=[('LS001', 'Concept Note'), ('LS002', 'Pipeline Taskforce Review'), ('LS003', 'Pipeline Taskforce Selection'), ('LS004', 'Preparation/LLF'), ('LS005', 'TRC clearance'), ('LS006', 'IC endorsed'), ('LS007', 'IsDB Annual Work Plan (AWP)'), ('LS008', 'Preparations'), ('LS009', 'Appraisal'), ('LS010', 'BED Approved'), ('LS011', 'Signature'), ('LS012', 'Effective'), ('LS013', 'Implementing'), ('LS014', 'Mid-Term Review'), ('LS015', 'Substantially Complete'), ('LS016', 'Closed'), ('LS017', 'Suspended'), ('LS018', 'Cancelled')], max_length=30),
        ),
        migrations.RunPython(to_ls_codes, to_old_values),
    ]
