# Generated by Django 5.0.6 on 2026-09-12 12:09

import apps.spatial.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0026_lifecycle_stages_ls_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('source_format', models.CharField(choices=[('geojson', 'GeoJSON'), ('kml', 'KML'), ('kmz', 'KMZ'), ('gpx', 'GPX'), ('gpkg', 'GeoPackage'), ('shp_zip', 'Shapefile (ZIP)')], max_length=10)),
                ('original_file', models.FileField(blank=True, help_text='The file as uploaded. Served only through the download endpoint, never as a direct storage URL.', null=True, upload_to=apps.spatial.models.gis_asset_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('original_size_bytes', models.PositiveIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, help_text='Of the original file, for traceability.', max_length=64)),
                ('feature_count', models.PositiveIntegerField(default=0)),
                ('geometry_types', models.JSONField(blank=True, default=list, help_text='Distinct geometry types found, e.g. ["Point", "Polygon"].')),
                ('bbox_min_x', models.FloatField(blank=True, null=True)),
                ('bbox_min_y', models.FloatField(blank=True, null=True)),
                ('bbox_max_x', models.FloatField(blank=True, null=True)),
                ('bbox_max_y', models.FloatField(blank=True, null=True)),
                ('layer_color', models.CharField(default='#E2725B', help_text='Hex colour used to draw the layer on the project map.', max_length=7)),
                ('is_visible_default', models.BooleanField(default=True, help_text='Whether the layer is drawn when the map first opens.')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=10)),
                ('error_detail', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_assets', to='project.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spatial_assets_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GIS asset',
                'db_table': 'gis_asset',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SpatialAssetFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, help_text='Best-effort display name read from the source attributes.', max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='spatial.spatialasset')),
            ],
            options={
                'db_table': 'gis_asset_feature',
            },
        ),
        migrations.AddIndex(
            model_name='spatialasset',
            index=models.Index(fields=['project', 'is_active'], name='gis_asset_project_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialassetfeature',
            index=models.Index(fields=['asset'], name='gis_feature_asset_idx'),
        ),
    ]
