# Generated by Django 5.0.6 on 2026-09-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialasset',
            name='layer_color',
            field=models.CharField(default='#0EB584', help_text='Hex colour used to draw the layer on the project map.', max_length=7),
        ),
    ]
