# Generated by Django 5.0.6 on 2026-07-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossCuttingTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'cross_cutting_theme',
            },
        ),
    ]
