# Generated by Django 5.0.6 on 2026-07-17 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_crosscuttingtheme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='regionalhub',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='donor',
            name='color',
            field=models.CharField(blank=True, help_text='Couleur institutionnelle (#RRGGBB).', max_length=7),
        ),
        migrations.AddField(
            model_name='donor',
            name='committed_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Engagement annonce au LLF2.', max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_type',
            field=models.CharField(blank=True, choices=[('bilateral', 'Bilateral'), ('multilateral', 'Multilateral'), ('foundation', 'Fondation'), ('humanitarian', 'Humanitaire')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='origin_iso2',
            field=models.CharField(blank=True, help_text="Code ISO2 du pays d'origine (ex. AE, SA, QA, US). Champ libre et non FK : les pays d'origine des bailleurs ne sont pas des pays du portefeuille et n'ont rien a faire dans le referentiel country. Laisser vide pour les institutions multilaterales (IsDB, ISFD), qui n'ont pas de drapeau national.", max_length=2),
        ),
        migrations.AddField(
            model_name='donor',
            name='short_name',
            field=models.CharField(blank=True, help_text='Sigle, ex. KSRelief.', max_length=20),
        ),
        migrations.AddField(
            model_name='regionalhub',
            name='city',
            field=models.CharField(blank=True, help_text="Ville d'implantation du hub.", max_length=100),
        ),
        migrations.AddField(
            model_name='regionalhub',
            name='color',
            field=models.CharField(blank=True, help_text="Couleur d'identification (#RRGGBB) pour les vues.", max_length=7),
        ),
        migrations.CreateModel(
            name='ImplementingAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('agency_type', models.CharField(choices=[('government', 'Gouvernement'), ('national_agency', 'Agence nationale'), ('un_agency', 'Agence ONU'), ('ngo', 'ONG'), ('private', 'Secteur prive')], max_length=20)),
                ('country', models.ForeignKey(blank=True, help_text='Vide pour les agences internationales (ONU, ONG multi-pays).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementing_agencies', to='reference.country')),
            ],
            options={
                'verbose_name_plural': 'implementing agencies',
                'db_table': 'implementing_agency',
                'ordering': ['name'],
            },
        ),
    ]
