# Generated by Django 5.0.6 on 2026-07-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_alter_country_options_alter_donor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL du logo officiel (Blob Storage ou site du bailleur). Conformement au principe du projet, aucune image n'est stockee en base64 — uniquement des URL. A defaut, un monogramme colore est affiche."),
        ),
        migrations.AddField(
            model_name='implementingagency',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL du logo officiel. A defaut, un monogramme est affiche.'),
        ),
        migrations.AddField(
            model_name='sdg',
            name='color',
            field=models.CharField(blank=True, help_text="Couleur officielle ONU de l'ODD (#RRGGBB). Le systeme affiche une tuile numerotee a cette couleur : les pictogrammes officiels des ODD sont des marques de l'ONU soumises a des regles d'usage, ils ne sont donc pas reproduits ici.", max_length=7),
        ),
        migrations.AddField(
            model_name='sector',
            name='color',
            field=models.CharField(blank=True, help_text='Couleur identitaire du secteur (#RRGGBB).', max_length=7),
        ),
        migrations.AddField(
            model_name='sector',
            name='icon',
            field=models.CharField(choices=[('health', 'Sante (croix medicale)'), ('agriculture', 'Agriculture (epi)'), ('infrastructure', 'Infrastructure (batiment)'), ('gender', 'Genre (symbole Venus)'), ('climate', 'Climat (feuille)'), ('water', 'Eau (goutte)'), ('education', 'Education (livre)'), ('generic', 'Generique (losange)')], default='generic', help_text="Pictogramme illustratif. Rendu en SVG cote frontend plutot qu'en emoji : les emojis ne s'affichent pas de maniere fiable selon le systeme d'exploitation.", max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='color',
            field=models.CharField(blank=True, help_text="Couleur institutionnelle (#RRGGBB), utilisee en repli quand aucun logo n'est fourni.", max_length=7),
        ),
        migrations.AlterField(
            model_name='donor',
            name='committed_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Engagement au LLF2, en USD. A renseigner depuis les chiffres officiels de la LLF MU : les engagements publies varient selon la phase et melent subventions, prets concessionnels et waqf.', max_digits=16, null=True),
        ),
    ]
