# Generated by Django 5.0.6 on 2026-07-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_donor_logo_url_implementingagency_logo_url_sdg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='logo_url',
            field=models.CharField(blank=True, help_text="Chemin ou URL du logo officiel. Accepte un asset servi par l'application (/logos/donors/isdb.png) ou une URL absolue (Blob Storage). Conformement au principe du projet, aucune image n'est stockee en base64. A defaut, un monogramme colore est affiche.", max_length=300),
        ),
        migrations.AlterField(
            model_name='implementingagency',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Chemin ou URL du logo officiel. A defaut, un monogramme est affiche.', max_length=300),
        ),
    ]
