# Generated by Django 5.0.6 on 2026-07-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_alter_donor_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, help_text="POL-1.07 : pas de suppression definitive. Un element desactive reste attache aux donnees qui le referencent deja, mais n'est plus proposable pour de nouvelles saisies."),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_active',
            field=models.BooleanField(default=True, help_text="POL-1.07 : pas de suppression definitive. Un element desactive reste attache aux donnees qui le referencent deja, mais n'est plus proposable pour de nouvelles saisies."),
        ),
        migrations.AddField(
            model_name='implementingagency',
            name='is_active',
            field=models.BooleanField(default=True, help_text="POL-1.07 : pas de suppression definitive. Un element desactive reste attache aux donnees qui le referencent deja, mais n'est plus proposable pour de nouvelles saisies."),
        ),
        migrations.AddField(
            model_name='regionalhub',
            name='is_active',
            field=models.BooleanField(default=True, help_text="POL-1.07 : pas de suppression definitive. Un element desactive reste attache aux donnees qui le referencent deja, mais n'est plus proposable pour de nouvelles saisies."),
        ),
        migrations.AddField(
            model_name='sector',
            name='is_active',
            field=models.BooleanField(default=True, help_text="POL-1.07 : pas de suppression definitive. Un element desactive reste attache aux donnees qui le referencent deja, mais n'est plus proposable pour de nouvelles saisies."),
        ),
    ]
