# Generated by Django 5.0.6 on 2026-07-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_gadmarea_gadm_uid_gadmarea_name_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadmarea',
            name='gadm_uid',
            field=models.CharField(help_text="Identifiant unique GADM (ex. SEN.1_1, SEN.1.2_1). Clé d'idempotence.", max_length=40, unique=True),
        ),
    ]
