# Generated by Django 5.0.6 on 2026-09-08 08:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0011_sector_pillar_naming'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalEarthLake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ne_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('scalerank', models.PositiveSmallIntegerField(default=0)),
                ('min_zoom', models.FloatField(default=0)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'ne_lake',
                'ordering': ['scalerank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NaturalEarthPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ne_id', models.BigIntegerField(help_text='Natural Earth NE_ID, stable across releases.', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('adm0_a3', models.CharField(blank=True, max_length=3)),
                ('featurecla', models.CharField(blank=True, max_length=50)),
                ('is_capital', models.BooleanField(default=False, help_text='FEATURECLA is an Admin-0 capital.')),
                ('scalerank', models.PositiveSmallIntegerField(default=0)),
                ('min_zoom', models.FloatField(default=0)),
                ('pop_max', models.BigIntegerField(default=0)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'ne_place',
                'ordering': ['scalerank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NaturalEarthCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.PositiveSmallIntegerField(choices=[(10, '1:10m'), (50, '1:50m')])),
                ('adm0_a3', models.CharField(help_text='Natural Earth ADM0_A3, unique per resolution (ISO_A3 is -99 for some).', max_length=3)),
                ('iso_a3', models.CharField(blank=True, max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('name_long', models.CharField(blank=True, max_length=150)),
                ('label_x', models.FloatField(blank=True, help_text='Label anchor longitude.', null=True)),
                ('label_y', models.FloatField(blank=True, help_text='Label anchor latitude.', null=True)),
                ('scalerank', models.PositiveSmallIntegerField(default=0)),
                ('min_zoom', models.FloatField(default=0, help_text='Natural Earth MIN_ZOOM hint.')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'ne_country',
                'ordering': ['scale', 'name'],
                'unique_together': {('scale', 'adm0_a3')},
            },
        ),
        migrations.RunSQL(
            # One point per country for labels: a symbol layer on the polygon
            # itself would place a label in every tile the polygon touches.
            # Martin publishes the view as `ne_country_label`.
            sql="""
                CREATE VIEW ne_country_label AS
                SELECT id, scale, adm0_a3, iso_a3, name, scalerank, min_zoom,
                       ST_SetSRID(ST_MakePoint(label_x, label_y), 4326)::geometry(Point, 4326) AS geometry
                FROM ne_country
                WHERE label_x IS NOT NULL AND label_y IS NOT NULL;
            """,
            reverse_sql="DROP VIEW IF EXISTS ne_country_label;",
        ),
    ]
