# Generated by Django 5.0.6 on 2026-07-16 22:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('protocol', models.CharField(choices=[('oidc', 'OpenID Connect'), ('saml2', 'SAML 2.0')], default='oidc', max_length=10)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('metadata_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'identity_provider',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='Role systeme non supprimable (ex. Admin Global).')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('internal', 'Interne (staff MillenniumPromise / IsDB)'), ('external', 'Externe (PMU, hub regional, donateur, auditeur)')], default='internal', max_length=10)),
                ('auth_method', models.CharField(choices=[('password', 'Mot de passe local'), ('sso', 'SSO (Entra ID)')], default='sso', max_length=10)),
                ('idp_subject', models.CharField(blank=True, help_text='Identifiant unique cote fournisseur (sub claim OIDC).', max_length=255)),
                ('mfa_enrolled', models.BooleanField(default=False)),
                ('mfa_method', models.CharField(choices=[('none', 'Aucune'), ('app', "Application d'authentification"), ('sms', 'SMS')], default='none', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('identity_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='identity.identityprovider')),
            ],
            options={
                'db_table': 'app_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('module', models.CharField(choices=[('m1_config_access', "M1 - Configuration & Controle d'acces"), ('m2_results_indicators', 'M2 - Cadre de resultats & indicateurs'), ('m3_workplan', 'M3 - Plan de travail'), ('m4_collection', 'M4 - Collecte de donnees'), ('m5_validation', 'M5 - Validation'), ('m6_reporting', 'M6 - Restitution'), ('m7_gis', 'M7 - Cartographie'), ('m8_procurement', 'M8 - Achats'), ('m9_risk', 'M9 - Risques'), ('m10_quality', 'M10 - Qualite / Audit'), ('m11_admin', 'M11 - Administration')], max_length=30)),
                ('action', models.CharField(choices=[('create', 'Creer'), ('read', 'Consulter'), ('update', 'Modifier'), ('delete', 'Supprimer'), ('validate', 'Valider'), ('export', 'Exporter'), ('admin', 'Administrer')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'permission',
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='RBACException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('fund', 'Fonds (LLF2)'), ('hub', 'Hub regional'), ('project', 'Projet')], max_length=10)),
                ('scope_id', models.PositiveIntegerField(blank=True, null=True)),
                ('justification', models.TextField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_exceptions_approved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_exception',
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('fund', 'Fonds (LLF2)'), ('hub', 'Hub regional'), ('project', 'Projet')], max_length=10)),
                ('scope_id', models.PositiveIntegerField(blank=True, help_text="ID de l'objet cible (hub, projet...). Vide si scope_type=global.", null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_granted', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='identity.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_assignment',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='identity.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='identity.role')),
            ],
            options={
                'db_table': 'role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
