# Generated by Django 5.0.6 on 2026-07-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('create', 'Creer'), ('read', 'Consulter'), ('update', 'Modifier'), ('delete', 'Supprimer'), ('submit', 'Soumettre'), ('review', 'Reviser'), ('validate', 'Valider'), ('export', 'Exporter'), ('admin', 'Administrer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rbacexception',
            name='scope_type',
            field=models.CharField(choices=[('global', 'Global'), ('fund', 'Fonds (LLF2)'), ('hub', 'Hub regional'), ('project', 'Projet'), ('donor', "Projets d'un bailleur")], max_length=10),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='scope_type',
            field=models.CharField(choices=[('global', 'Global'), ('fund', 'Fonds (LLF2)'), ('hub', 'Hub regional'), ('project', 'Projet'), ('donor', "Projets d'un bailleur")], max_length=10),
        ),
    ]
