# Generated by Django 5.0.6 on 2026-07-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_alter_permission_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(help_text="Identifiant fonctionnel de l'utilisateur, unique. Django n'impose pas cette unicite par defaut : sans elle, un compte local et son jumeau SSO peuvent porter la meme adresse, ce qui rend impossible de savoir sous quelle identite on agit.", max_length=254, unique=True),
        ),
    ]
