# Generated by Django 5.0.6 on 2026-07-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_alter_appuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='auth_method',
            field=models.CharField(choices=[('password', 'Local password'), ('sso', 'SSO (Entra ID)')], default='sso', max_length=10),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='mfa_method',
            field=models.CharField(choices=[('none', 'None'), ('app', 'Authenticator app'), ('sms', 'SMS')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(choices=[('internal', 'Internal (MillenniumPromise / IsDB staff)'), ('external', 'External (PMU, regional hub, donor, auditor)')], default='internal', max_length=10),
        ),
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('submit', 'Submit'), ('review', 'Review'), ('validate', 'Validate'), ('export', 'Export'), ('admin', 'Administer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rbacexception',
            name='scope_type',
            field=models.CharField(choices=[('global', 'Global'), ('fund', 'Fund (LLF2)'), ('hub', 'Regional hub'), ('project', 'Project'), ('donor', 'Projects of a donor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='scope_type',
            field=models.CharField(choices=[('global', 'Global'), ('fund', 'Fund (LLF2)'), ('hub', 'Regional hub'), ('project', 'Project'), ('donor', 'Projects of a donor')], max_length=10),
        ),
    ]
